apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: cart # Deploymentset name
  namespace: roboshop  
  labels: 
    app: cart 
    project: roboshop 
    tier: app  
spec: 
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: # replicaset labels 
      app: cart 
      project: roboshop 
      tier: app  

  template: # Pod definition 
    metadata:
      name: cart # Pod name# ACTUAL POD NAME WILL BE DIFFERENT AFTER Kubectl apply
      labels:
        app: cart 
        project: roboshop 
        tier: app  
    spec: 
      containers:
      - name: cart  # container name 
        image: "devopsprocloudaws/cart:{{ .Values.deployment.imageVersion }}"
        ports: 
        - containerPort: 8080 
        envFrom:
        - configMapRef:
            name: cart 
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"

 
