apiVersion: v1 
kind: Service
metadata:
  name: frontend
  namespace: roboshop 
spec: 
  type: LoadBalancer
  selector: # selecting the Pod by using the same Pod labels 
    app: frontend 
    project: roboshop 
    tier: frontend
  ports:
  - protocol: TCP
    port: 80 # service port 
    targetPort: 80 # container port