apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: catalogue # Deploymentset name 
  namespace: roboshop 
  labels: 
    app: catalogue 
    project: roboshop 
    tier: app  
spec: 
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: # replicaset labels 
      app: catalogue 
      project: roboshop 
      tier: app  

  template: # Pod definition 
    metadata:
      name: catalogue # Pod name# ACTUAL POD NAME WILL BE DIFFERENT AFTER Kubectl apply
      labels:
        app: catalogue 
        project: roboshop 
        tier: app  
    spec: 
      containers:
      - name: catalogue  # container name 
        image: "devopsprocloudaws/catalogue:{{ .Values.deployment.imageVersion }}"
        ports: 
        - containerPort: 8080 
        envFrom:
        - configMapRef:
            name: catalogue 
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"

 
